import { z } from 'zod';

/**
 * Diet of a recipe, from strictest to least: a recipe fits a person whose diet allows its level.
 * `eggs` = vegetarian plus eggs: "vegetarian" here excludes eggs, as in many South Asian homes.
 */
export const RECIPE_DIETS = ['vegan', 'vegetarian', 'eggs', 'meat'] as const;
export type RecipeDiet = (typeof RECIPE_DIETS)[number];

/** A person's diet preference (UserSettings.diet). `any` applies no filter. */
export const DIETS = ['any', 'eggs', 'vegetarian', 'vegan'] as const;
export type Diet = (typeof DIETS)[number];

/** Cuisines of the local set; AI recipes may name others (shown as written). */
export const CUISINES = [
  'south_asian',
  'mexican',
  'italian',
  'middle_eastern',
  'east_asian',
  'everyday',
] as const;
export type Cuisine = (typeof CUISINES)[number];

export const recipeIngredientSchema = z.object({
  /** What the cook reads, e.g. "Spinach". */
  name: z.string().trim().min(1).max(80),
  /** Food dictionary id used to match the pantry (SRS 8.5). Omitted for water and unknowns. */
  foodId: z.string().optional(),
  amount: z.number().min(0).nullable(),
  unit: z.string().max(30).nullable(),
  /** Kitchen basics (salt, oil, water) are assumed on hand and never count as missing. */
  basic: z.literal(true).optional(),
  /** Nice to have: never counts as missing. */
  optional: z.literal(true).optional(),
});
export type RecipeIngredient = z.infer<typeof recipeIngredientSchema>;

export const recipeStepSchema = z.object({
  title: z.string().trim().min(1).max(80),
  text: z.string().trim().min(1).max(1200),
  timerSeconds: z
    .number()
    .int()
    .min(1)
    .max(6 * 3600)
    .optional(),
});
export type RecipeStep = z.infer<typeof recipeStepSchema>;

/** SRS 10 Recipe: from the local set (`local`) or generated by AI and kept on the API (`ai`). */
export const recipeSchema = z.object({
  id: z.string().min(1).max(80),
  source: z.enum(['local', 'ai']),
  title: z.string().trim().min(1).max(100),
  /** One of CUISINES for local recipes; AI may use any cuisine name. */
  cuisine: z.string().trim().min(1).max(40),
  minutes: z.number().int().min(1).max(600),
  servings: z.number().int().min(1).max(20),
  diet: z.enum(RECIPE_DIETS),
  ingredients: z.array(recipeIngredientSchema).min(1).max(40),
  steps: z.array(recipeStepSchema).min(1).max(30),
});
export type Recipe = z.infer<typeof recipeSchema>;

/** A local recipe as written in `data/*.ts`. Original text, CC0. */
export type LocalRecipe = Omit<Recipe, 'source' | 'cuisine'> & { cuisine: Cuisine };

/** SRS 10 UserSettings recipe fields ("What the AI should know", PRO-3). */
export const recipePrefsSchema = z.object({
  diet: z.enum(DIETS),
  /** Preferred cuisines; empty = any (REC-7). Soft: they only lift matching recipes. */
  cuisines: z.array(z.string().trim().min(1).max(40)).max(12),
  /** Hard limit on cooking time; null = no limit. */
  maxMinutes: z.number().int().min(5).max(600).nullable(),
  /** Ingredients never to suggest (allergies, dislikes). Hard filter. */
  avoid: z.array(z.string().trim().min(1).max(40)).max(30),
});
export type RecipePrefs = z.infer<typeof recipePrefsSchema>;

export const DEFAULT_RECIPE_PREFS: RecipePrefs = {
  diet: 'any',
  cuisines: [],
  maxMinutes: null,
  avoid: [],
};
